emin_heating_interval: 1
emin_heating_step: 300
emin_steps: 10
emin_target_temp: 300
emin_tolerance: 5 * kilojoule_per_mole / nanometer
export_prmtop: true
ff_protein: amber14-all.xml
ff_protein_openff: ff14sb_off_impropers_0.0.3.offxml
ff_small_molecule_openff: openff-2.0.0.offxml
ff_water: amber14/tip3pfb.xml
integrator_friction: 1.0
integrator_temperature: 300.0
integrator_timestep: 0.002
md_anisotropic: false
md_barostat_freq: 25
md_harmonic_restraint: false
md_load_state: true
md_npt: false
md_pressure: 1.0
md_restrained_residues: []
md_save_interval: 10
md_steps: 1000
mmpbsa: false
monitor_energy_threshold: 100.0
monitor_temp_threshold: 2.0
monitor_window: 10
path_amber_complex: /home/omarpag1991/easy-md/example/output/amber/amber_complex.prmtop
path_amber_ligand: /home/omarpag1991/easy-md/example/output/amber/amber_ligand.prmtop
path_amber_receptor: /home/omarpag1991/easy-md/example/output/amber/amber_receptor.prmtop
path_amber_solvated: /home/omarpag1991/easy-md/example/output/amber/amber_complex_solvated.prmtop
path_base: /home/omarpag1991/easy-md/example
path_emin_state: /home/omarpag1991/easy-md/example/output/emin/emin.xml
path_emin_structure: /home/omarpag1991/easy-md/example/output/emin/emin.pdb
path_ligand: /home/omarpag1991/easy-md/example/4w52_C_EPE.sdf
path_md_checkpoint: /home/omarpag1991/easy-md/example/output/md/md_checkpoint_id_0.chk
path_md_image: /home/omarpag1991/easy-md/example/output/md/final_md_trajectory_id_0.dcd
path_md_log: /home/omarpag1991/easy-md/example/output/md/md_id_0.log
path_md_state: /home/omarpag1991/easy-md/example/output/md/md_state_id_0.xml
path_md_trajectory: /home/omarpag1991/easy-md/example/output/md/md_temp_trajetory_id_0.dcd
path_mmpbsa_in: /home/omarpag1991/easy-md/example/output/mmpbsa/mmpbsa.in
path_mmpbsa_results: /home/omarpag1991/easy-md/example/output/mmpbsa/FINAL_RESULTS_MMPBSA.dat
path_openff_interchange: /home/omarpag1991/easy-md/example/output/prep/openff_interchange.pdb
path_openff_topology: /home/omarpag1991/easy-md/example/output/prep/openff_topology.json
path_openmm_system: /home/omarpag1991/easy-md/example/output/prep/openmm_system.xml
path_openmm_topology: /home/omarpag1991/easy-md/example/output/prep/openmm_topology.pkl
path_protein: /home/omarpag1991/easy-md/example/4W52.pdb
path_protein_solvated: /home/omarpag1991/easy-md/example/output/prep/system_solvated.pdb
path_rmsd_ligand_output: /home/omarpag1991/easy-md/example/output/analysis/analysis_rmsd_ligand.pkl
path_rmsd_output: /home/omarpag1991/easy-md/example/output/analysis/analysis_rmsd.pkl
path_rmsf_output: /home/omarpag1991/easy-md/example/output/analysis/analysis_rmsf.log
platform_name: CPU
platform_precision: mixed
rmsd_ligand_selection: resname UNK
rmsd_selection: protein and name CA
rmsf_selection: protein and name CA
solv_box_buffer: 2.5
solv_ionic_strength: 0.15
solv_model: tip3p
solv_negative_ion: Cl-
solv_pH: 7.0
solv_positive_ion: Na+
