emin_heating_interval: 1
emin_heating_step: 300
emin_steps: 10
emin_target_temp: 300
emin_tolerance: 5 * kilojoule_per_mole / nanometer
export_prmtop: true
ff_protein: amber14-all.xml
ff_protein_openff: ff14sb_off_impropers_0.0.3.offxml
ff_small_molecule_openff: openff-2.0.0.offxml
ff_water: amber14/tip3pfb.xml
integrator_friction: 1.0
integrator_temperature: 300.0
integrator_timestep: 0.002
md_anisotropic: false
md_barostat_freq: 25
md_harmonic_restraint: false
md_load_state: true
md_npt: false
md_pressure: 1.0
md_restrained_residues: []
md_save_interval: 10
md_steps: 1000
platform_name: CPU
platform_precision: mixed
rmsd_ligand_selection: resname UNK
rmsd_selection: protein and name CA
rmsf_selection: protein and name CA
solv_box_buffer: 2.5
solv_ionic_strength: 0.15
solv_model: tip3p
solv_negative_ion: Cl-
solv_pH: 7.0
solv_positive_ion: Na+
