name: easymd
channels:
  - conda-forge
  - defaults

dependencies:
  # Core packages
  - python=3.9
  - openmm=8.0.0
  - pdbfixer
  - mdanalysis
  - pandas
  - matplotlib
  - numpy
  - scipy
  - tqdm
  - pyyaml
  - h5py
  - jupyter
  - notebook

  # Python packages to be installed with pip
  - pip
  - pip:
      - rdkit
# NOTE: ambertools and openff-toolkit need to be installed manually
# See DOCKER_README.md for instructions
